version: '3.7'
# version: '2.3'

services:
  fastapi:
    build:
      context: ./services/fastapi
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - 8000:8000
    expose:
      - 8000
    restart: unless-stopped

  nginx:
    container_name: nginx
    build: ./services/nginx
    ports:
      - 5000:80
    restart: unless-stopped
    depends_on:
      - fastapi
